<?xml version="1.0" encoding="UTF-8"?>
<!--
    =====================================================
    XSLT STYLESHEET - FULL PAGE
    =====================================================
    This file transforms XML data into a full HTML page.

    XSLT Concepts Covered:
      - <xsl:template match="/">     → Matches the root of the XML
      - <xsl:for-each select="...">  → Loops over XML elements
      - <xsl:value-of select="...">  → Outputs the text of an element
      - <xsl:if test="...">          → Conditional output
      - <xsl:sort select="...">      → Sorts elements

    Input XML (from XsltProductAction):
        <products>
            <product id="1">
                <name>Laptop</name>
                <category>Electronics</category>
                <price>999.99</price>
                <description>...</description>
            </product>
            ...
        </products>

    Output: A full HTML page with a styled product table.
    =====================================================
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <!-- Disable output method escaping for clean HTML -->
    <xsl:output method="html" encoding="UTF-8" doctype-public="-//W3C//DTD XHTML 1.0 Transitional//EN"/>

    <!--
        =====================================================
        ROOT TEMPLATE
        =====================================================
        match="/" means this template applies to the
        root node of the XML document.
        Everything here becomes the output HTML.
        =====================================================
    -->
    <xsl:template match="/">
        <html lang="en">
        <head>
            <meta charset="UTF-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <title>CXSLT Product Demo</title>
            <link rel="stylesheet" href="css/style.css"/>
            <!-- HTMX for the "Load via HTMX" button -->
            <script src="https://unpkg.com/htmx.org@1.9.10"></script>
        </head>
        <body>

            <header class="app-header">
                <h1>🔄 CXSLT Product Demo</h1>
                <p class="subtitle">This page is rendered entirely by XSLT transforming XML data</p>
                <a href="indexAction" class="back-link">← Back to Home</a>
            </header>

            <main class="container">

                <!-- Explanation card -->
                <section class="concept-card">
                    <h2>How CXSLT Works</h2>
                    <p>
                        The server generated an XML document from Java code.
                        This XSLT stylesheet transformed that XML into the HTML
                        you see right now — entirely on the server, before sending
                        anything to the browser.
                    </p>
                    <div class="flow-diagram">
                        <span class="flow-step">Java Action</span>
                        <span class="flow-arrow">→</span>
                        <span class="flow-step">XML (DOM)</span>
                        <span class="flow-arrow">→</span>
                        <span class="flow-step">XSLT Transform</span>
                        <span class="flow-arrow">→</span>
                        <span class="flow-step">HTML Output</span>
                    </div>
                </section>

                <!-- HTMX button to load just the list fragment via XSLT -->
                <section class="list-section">
                    <div class="section-header">
                        <h2>Products (via XSLT)</h2>
                        <!--
                            This button uses HTMX to load the product list
                            fragment generated by a DIFFERENT XSLT stylesheet
                            (productList.xslt) — demonstrating HTMX + CXSLT together.
                        -->
                        <button class="btn btn-htmx"
                                hx-get="xsltProductListAction"
                                hx-target="#xslt-product-list"
                                hx-swap="innerHTML"
                                hx-indicator="#xslt-spinner"
                        >
                            ⚡ Reload via HTMX
                        </button>
                        <span id="xslt-spinner" class="htmx-indicator spinner">⟳</span>
                    </div>

                    <!-- The product table (rendered by XSLT below) -->
                    <div id="xslt-product-list">
                        <xsl:call-template name="productTable"/>
                    </div>
                </section>

                <!-- Product count summary -->
                <section class="summary-section">
                    <h2>Summary</h2>
                    <p>
                        Total products: <strong><xsl:value-of select="count(products/product)"/></strong>
                    </p>
                </section>

            </main>

            <footer class="app-footer">
                <p>🔄 This entire page was generated by XSLT — no JSP involved!</p>
            </footer>

        </body>
        </html>
    </xsl:template>

    <!--
        =====================================================
        NAMED TEMPLATE: productTable
        =====================================================
        This is a reusable "function" in XSLT.
        We call it with <xsl:call-template name="productTable"/>
        It generates the HTML table for all products.
        =====================================================
    -->
    <xsl:template name="productTable">
        <table class="product-table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <!--
                    =====================================================
                    xsl:for-each
                    =====================================================
                    Loops over every <product> element inside <products>.
                    Inside this loop, . (dot) refers to the current product.
                    =====================================================
                -->
                <xsl:for-each select="products/product">

                    <!-- Sort products by id alphabetically -->
                    <xsl:sort select="@id" order="ascending"/>

                    <tr class="product-row">
                        <!-- @id means the "id" attribute of <product> -->
                        <td><xsl:value-of select="@id"/></td>
                        <td><xsl:value-of select="name"/></td>
                        <td>
                            <span class="badge">
                                <xsl:value-of select="category"/>
                            </span>
                        </td>
                        <td class="price">
                            $<xsl:value-of select="price"/>
                        </td>
                        <td><xsl:value-of select="description"/></td>
                    </tr>
                </xsl:for-each>
            </tbody>
        </table>
    </xsl:template>

</xsl:stylesheet>
